version: '3.3'
services:
  api:
    build: './service'
    ports:
      - '8000:80'
    environment:
      - MONGO_ADDRESS=mongodb://db:27017
    volumes:
      - '.:/go/src/app'
    depends_on:
      - 'db'
  db:
    image: 'mongo:latest'
    ports:
      - '5000:27017'
